object Versions {
    const val mock = "5.5.0"
    const val mockitoKotlin = "5.0.0"
    const val coreTest = "2.1.0"
    const val coroutineTest = "1.7.3"
    const val coreKtx = "1.15.0"
    const val junit = "4.13.2"
    const val junitVersion = "1.2.1"
    const val espressoCore = "3.6.1"
    const val lifecycleRuntimeKtx = "2.8.7"
    const val lifecycleViewModelKtx = "2.6.1"
    const val activityCompose = "1.8.0"
    const val composeBom = "2024.04.01"
    const val appCompat = "1.7.0"
    const val material = "1.12.0"
    const val hilt = "2.48"
    const val hiltCompiler = "2.28-alpha"
    const val navigationCompose = "2.8.4"
    const val hiltNavigationCompose = "1.0.0"
    const val retrofit = "2.9.0"
    const val okHttp = "4.11.0"
    const val gsonConverter = "2.9.0"
    const val moshi = "1.15.0"
    const val moshiConverter = "2.9.0"
    const val loggingInterceptor = "4.11.0"
    const val coroutines = "1.7.3"
    const val coreSplashscreen = "1.0.1"
    const val coilCompose = "2.4.0"

}